local helpers = require("tests.helpers")
local fixtures = require("tests.fixtures")

describe("codeview.vcs", function()
  local vcs, config

  before_each(function()
    helpers.unload()
    vcs = require("codeview.vcs")
    config = require("codeview.config")
  end)

  after_each(function()
    helpers.unload()
  end)

  describe("parse_range", function()
    it("reads one commit", function()
      local parsed = assert(vcs.parse_range("abc123"))
      assert.are.equal("single", parsed.kind)
      assert.are.equal("abc123", parsed.to)
      assert.is_nil(parsed.from)
      assert.are.equal("abc123", parsed.spec)
    end)

    it("reads a two dot range", function()
      local parsed = assert(vcs.parse_range("main..feature"))
      assert.are.equal("range", parsed.kind)
      assert.are.equal("main", parsed.from)
      assert.are.equal("feature", parsed.to)
    end)

    it("reads a three dot range", function()
      local parsed = assert(vcs.parse_range("main...feature"))
      assert.are.equal("triple", parsed.kind)
      assert.are.equal("main", parsed.from)
      assert.are.equal("feature", parsed.to)
    end)

    it("fills an empty side with HEAD", function()
      assert.are.equal("HEAD", assert(vcs.parse_range("main..")).to)
      assert.are.equal("HEAD", assert(vcs.parse_range("..main")).from)
    end)

    it("keeps the dots of a revision that has no range", function()
      local parsed = assert(vcs.parse_range("v1.2.3"))
      assert.are.equal("single", parsed.kind)
      assert.are.equal("v1.2.3", parsed.to)
    end)

    it("splits a range of two dotted revisions", function()
      local parsed = assert(vcs.parse_range("v1.2..v1.3"))
      assert.are.equal("range", parsed.kind)
      assert.are.equal("v1.2", parsed.from)
      assert.are.equal("v1.3", parsed.to)
    end)

    it("trims the text", function()
      local parsed = assert(vcs.parse_range("  main .. feature  "))
      assert.are.equal("main", parsed.from)
      assert.are.equal("feature", parsed.to)
    end)

    it("rejects an empty text", function()
      local parsed, err = vcs.parse_range("   ")
      assert.is_nil(parsed)
      assert.are.equal("invalid_arg", err.code)
    end)

    it("rejects a value that is not a string", function()
      local parsed, err = vcs.parse_range(nil)
      assert.is_nil(parsed)
      assert.are.equal("invalid_arg", err.code)
    end)
  end)

  describe("get", function()
    it("loads the git backend", function()
      local backend, err = vcs.get("git")
      assert.is_nil(err)
      assert.are.equal("git", backend.name)
      assert.are.equal("function", type(backend.detect))
      assert.are.equal("function", type(backend.available))
    end)

    it("loads the jj backend", function()
      local backend, err = vcs.get("jj")
      assert.is_nil(err)
      assert.are.equal("jj", backend.name)
      assert.are.equal("function", type(backend.detect))
      assert.are.equal("function", type(backend.available))
    end)

    it("tries jj before git", function()
      assert.are.same({ "jj", "git" }, vcs.order)
    end)

    it("rejects an unknown backend", function()
      local backend, err = vcs.get("hg")
      assert.is_nil(backend)
      assert.are.equal("invalid_arg", err.code)
    end)
  end)

  describe("detect", function()
    local fixture = fixtures.git()

    it("finds the repository with the auto backend", function()
      local repo, err = vcs.detect(fixture.dir)
      assert.is_nil(err)
      assert.are.equal("git", repo.backend)
      assert.are.equal(fixture.root, repo.root)
    end)

    it("finds the repository with a forced backend", function()
      local repo = assert(vcs.detect(fixture.dir, { backend = "git" }))
      assert.are.equal("git", repo.backend)
    end)

    it("reads the backend from the configuration", function()
      config.setup({ backend = "git" })
      local repo = assert(vcs.detect(fixture.dir))
      assert.are.equal("git", repo.backend)
      config.reset()
    end)

    it("reports a forced backend that is not installed", function()
      local jj = require("codeview.vcs.jj")
      local available = jj.available
      jj.available = function()
        return false
      end
      local repo, err = vcs.detect(fixture.dir, { backend = "jj" })
      jj.available = available
      assert.is_nil(repo)
      assert.are.equal("unsupported", err.code)
      assert.is_truthy(tostring(err):find("$PATH", 1, true), tostring(err))
    end)

    it("rejects an unknown backend name", function()
      local repo, err = vcs.detect(fixture.dir, { backend = "hg" })
      assert.is_nil(repo)
      assert.are.equal("invalid_arg", err.code)
    end)

    it("reports a directory outside a repository", function()
      local outside = fixtures.tempdir("codeview-outside")
      local repo, err = vcs.detect(outside)
      assert.is_nil(repo)
      assert.are.equal("not_a_repo", err.code)
      vim.fn.delete(outside, "rf")
    end)

    it("detects asynchronously", function()
      local out, finished = {}, false
      vcs.detect(fixture.dir, nil, function(repo, err)
        out.repo, out.err, finished = repo, err, true
      end)
      assert.is_true(vim.wait(20000, function()
        return finished
      end, 10))
      assert.is_nil(out.err)
      assert.are.equal(fixture.root, out.repo.root)
    end)

    it("removes the fixture", function()
      fixture.cleanup()
      assert.are.equal(0, vim.fn.isdirectory(fixture.dir))
    end)
  end)
end)
